name = "Tastefully Enhanced"
version = "2.0.1+4.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "763401cc5b15e66352f496f01819d8e1756e964cff51adf46fea742873cdbf6a"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
