name = "Tastefully Enhanced"
version = "1.1.1+4.0.0-beta.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30ffe46fdeb7d6a5bd3fb6c42bfd866d6f7c3ac3a7755691180b8478c0ad00d2"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
