name = "Tastefully Enhanced"
version = "2.8.0+4.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4c70db2316c6ac5daae6093397ab47899c50b08557373ec05bedda5d686880e"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
