name = "Tastefully Enhanced"
version = "2.3.1+4.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8482b50d8b54392290d7c442295d7e26dbea1046bbb2374299a20e46fdf36cdb"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
