name = "Tastefully Enhanced"
version = "2.13.0+4.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45a7157e4c14315b0dc0d9c9a26ff622a5e57e30c33cc505575af6c11e12f175"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
