name = "Tastefully Enhanced"
version = "1.0.0+4.0.0-beta.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2afd8057f19d800515ae222967ac56468c32d2b9a395b41e866dde0ae63b2a8a"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
