name = "Tastefully Enhanced"
version = "1.0.0+4.0.0-beta.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fd804a84294507b0e13ed5736c0c0ad006c6ef1121daa2a82d1c20eda851b21"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
